Allow partial span validation on parent on only one date field
annkissam/acts_as_span pull request #24
Opened 2020-12-17 12:03 UTC by danielaSerban

- [Enrollment requirement](https://annkissam-team.monday.com/boards/332596247/pulses/883808047)

2020-12-17 14:23 UTC, izzergh requested changes
What you are testing is that you can remove the overlap validation entirely for a model - could you make a model for skipping start and another for skipping end, and test that the overlap validator still cares about the other one?

2020-12-17 14:23 UTC, izzergh commented on lib/acts_as_span/within_parent_date_span_validator.rb
> +      start_date_invalid || end_date_invalid
I would split this up into full `if`s; the lines are starting to get unwieldy

2020-12-17 14:27 UTC, danielaSerban commented
> What you are testing is that you can remove the overlap validation entirely for a model - could you make a model for skipping start and another for skipping end, and test that the overlap validator still cares about the other one?

Ayee, you're right. I'm gonna add some more tests.

2020-12-17 14:31 UTC, izzergh commented
Oof and it looks like CI broke...

2020-12-23 16:46 UTC, izzergh commented
@danielaSerban if you merge #25 into this, Travis will run properly (but if you merge this before #25 gets merged, you should bump the version since it locks Rails)

2022-08-17 10:49 UTC, merged

2022-08-24 22:42 UTC, izzergh commented
👀